# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JSON1' do

pod 'Alamofire'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JSON1

  target 'JSON1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JSON1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
